# -*- coding: utf-8 -*-
"""color_to_sketch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o8tzzpsluTt6BwgWzzDPsvHyEg-cWbiz
"""

import cv2
import numpy as np
from pathlib import Path


def photo_to_colored_edges(image_path: str, output_path: str,
                            canny_low: int = 50, canny_high: int = 150,
                            blur_radius: int = 3) -> np.ndarray:
    """
    Convert a photo to a colored edge drawing.
    Edge pixels take the color of the corresponding pixel in the original image.
    Everything else is white (like a blank canvas).

    Args:
        image_path:   path to input photo
        output_path:  path to save the colored edge drawing
        canny_low:    lower threshold for Canny edge detector
        canny_high:   upper threshold for Canny edge detector
        blur_radius:  gaussian blur radius before edge detection (odd number)

    Returns:
        colored edge image as numpy array (H, W, 3) BGR
    """
    # Load image
    img = cv2.imread(image_path)
    if img is None:
        raise FileNotFoundError(f"Could not load image: {image_path}")

    # Convert to grayscale for edge detection
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    # Blur slightly to reduce noise before edge detection
    blurred = cv2.GaussianBlur(gray, (blur_radius, blur_radius), 0)

    # Detect edges — result is a binary mask (255 = edge, 0 = background)
    edges = cv2.Canny(blurred, canny_low, canny_high)

    # Start with a white canvas
    result = np.ones_like(img) * 255  # white background

    # Where edges exist, copy the color from the original photo
    edge_mask = edges > 0             # boolean mask of edge pixels
    result[edge_mask] = img[edge_mask]

    # Save
    cv2.imwrite(output_path, result)
    return result


def process_dataset(input_dir: str, output_dir: str,
                    canny_low: int = 50, canny_high: int = 150,
                    blur_radius: int = 3):
    """
    Process an entire folder of images into colored edge drawings.
    Output folder structure mirrors input folder structure.
    Paired images share the same filename — easy to load for training.

    Args:
        input_dir:   folder of real photos  (your 'labels' / ground truth)
        output_dir:  folder to save colored edge drawings  (your 'inputs')
        canny_low:   lower Canny threshold
        canny_high:  upper Canny threshold
        blur_radius: gaussian blur radius (odd number)
    """
    input_path = Path(input_dir)
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)

    extensions = {".jpg", ".jpeg", ".png", ".bmp", ".tiff", ".webp"}
    image_files = [f for f in input_path.rglob("*") if f.suffix.lower() in extensions]

    if not image_files:
        print(f"No images found in {input_dir}")
        return

    print(f"Processing {len(image_files)} images...")

    success, failed = 0, 0
    for img_file in image_files:
        # Mirror subfolder structure in output
        relative = img_file.relative_to(input_path)
        out_file = output_path / relative
        out_file.parent.mkdir(parents=True, exist_ok=True)

        try:
            photo_to_colored_edges(
                str(img_file), str(out_file),
                canny_low=canny_low,
                canny_high=canny_high,
                blur_radius=blur_radius
            )
            success += 1
            if success % 100 == 0:
                print(f"  {success}/{len(image_files)} done...")
        except Exception as e:
            print(f"  FAILED {img_file.name}: {e}")
            failed += 1

    print(f"\nDone. {success} succeeded, {failed} failed.")
    print(f"Colored edge drawings saved to: {output_dir}")
    print(f"\nDataset pairs:")
    print(f"  Input  (colored edges) → {output_dir}/")
    print(f"  Output (real photos)   → {input_dir}/")


result = photo_to_colored_edges("house.jpg", "house_colored.jpg")